---
- hosts: 172.31.33.171
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myresult

  - name: i want to displays the task result
    debug:
       msg: "{{myresult}}"  

  - name: i want to install git on ubuntu
    apt:
      name: git
      state: present
    when: myresult.stderr =="" 