---
- hosts: webservers
  become: yes
  tasks: 
   - include_tasks: myfile.yml
   
   - name: i want to install webserver on ubuntu
     apt:
       name: apache2
       state: present
     when: ansible_os_family =="Debian"  
     notify: restart_server

   - name: copy static file into ansible node
     copy:
       src: static.txt
       dest: /home/ubuntu/static.txt
     when: ansible_os_family =="Debian"
     notify: restart_server

   - name: copy dyno file into ansible node
     template:
         src: dynofile.js2
         dest: /var/www/html/index.html
     when: ansible_os_family =="Debian"
     notify: restart_server


   - name: i wan to download remote file 
     get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.15/bin/apache-tomcat-8.0.15.tar.gz
        dest: /home/ubuntu/apache-tomcat-8.0.15.tar.gz
     force_basic_auth: yes
     when: ansible_os_family =="Debian"
     notify: restart_server  




     

   
  handlers:
   - name: restart_server
     service:
        name: apache2
        state: restarted


      
       





