---
- name: deploy prod app to server
  get_url:
     url: https://myappdemobucket.s3.ap-south-1.amazonaws.com/gameoflife.war
     dest: /opt/tomcat/webapps/gameoflife.war
     force_basic_auth: yes

